version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

    build:
      commands:
        - docker build -t mydockerhub/user-service:latest .

    post_build:
      commands:
        - docker push mydockerhub/user-service:latest
