apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-green
  labels:
    app: account-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
      version: green
  template:
    metadata:
      labels:
        app: account-service
        version: green
    spec:
      containers:
        - name: account-service
          image: account-service:latest
          ports:
            - containerPort: 5002
